global:
  scrape_interval:     10s
  evaluation_interval: 10s
  external_labels:
      monitor: 'sumus-monitoring'
rule_files:
  - 'alert.rules'
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "sumus_alertmanager:9093"

scrape_configs:
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
         - targets: ['localhost:9090','sumus_cadvisor:8080','sumus_node-exporter:9100']
  - job_name: 'netdata'
    metrics_path: '/api/v1/allmetrics'
    params:
      format: [prometheus]
    honor_labels: true
    scrape_interval: 5s
    static_configs:
         - targets: ['192.168.100.133:19999']
