route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            username: 'fernando.franceschi@sumus.com.br'
            channel: '#monitoring'
            api_url: 'https://hooks.slack.com/services/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'
